name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run command
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
            ls -la
            echo "$PRIVATE_KEY"
